"""Pydantic schemas for AI-powered Chatbot (/chat/respond)."""

from typing import List, Optional
from pydantic import BaseModel, Field


class ChatHistoryItem(BaseModel):
    """Previous exchange in the conversation."""
    role: str = Field(..., description="'user' or 'assistant' / 'bot'")
    text: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    """Input payload for generating a conversational AI response."""
    message: str = Field(..., min_length=1, description="Current message from the victim")
    history: List[ChatHistoryItem] = Field(default_factory=list, description="Recent conversation turns for context")
    language: str = Field(default="en", description="Target language ('en' for English, 'hi' for Hindi)")
    sentiment_label: Optional[str] = Field(default=None, description="Pre-computed sentiment ('positive', 'negative', 'neutral')")
    emotion_label: Optional[str] = Field(default=None, description="Dominant emotion (e.g. 'fear', 'sadness', 'anxiety')")
    victim_id: Optional[str] = Field(default=None, description="Anonymized ID of the victim")


class ChatResponse(BaseModel):
    """Output payload from the AI chatbot."""
    reply: str = Field(..., description="Conversational, empathetic response generated by the AI")
    crisis_flag: bool = Field(default=False, description="True if self-harm or imminent danger language was detected")
    language: str = Field(..., description="Language of the response")
    model_used: str = Field(..., description="Model identifier (e.g. 'gemini-1.5-flash' or 'saheli-fallback')")
